all: gauss laplace bell inversebel

gauss: gauss.cpp
	g++ -Wall gauss.cpp lodepng.cpp -o gauss

laplace: laplace.cpp
	g++ -Wall laplace.cpp lodepng.cpp -o laplace

bell: bell.cpp
	g++ -Wall bell.cpp lodepng.cpp -o bell

inversebel: inversebel.cpp
	g++ -Wall inversebel.cpp lodepng.cpp -o inversebell