all: gauss laplace bell inversebell

gauss: gauss.cpp
	g++ -Wall gauss.cpp lodepng.cpp -o gauss

laplace: laplace.cpp
	g++ -Wall laplace.cpp lodepng.cpp -o laplace

bell: bell.cpp
	g++ -Wall bell.cpp lodepng.cpp -o bell

inversebell: inversebell.cpp
	g++ -Wall inversebell.cpp lodepng.cpp -o inversebell