all: morphological scaling ripple twirl

morphological: morphological.cpp
	g++ -Wall morphological.cpp lodepng.cpp -o morphological

scaling: image_scaling.cpp
	g++ -Wall image_scaling.cpp lodepng.cpp -o scaling

ripple: ripple.cpp
	g++ -Wall ripple.cpp lodepng.cpp -o ripple

twirl: twirl.cpp
	g++ -Wall twirl.cpp lodepng.cpp -o twirl

